services:
  fly_user_group:
    class: Fly\UserBundle\Form\Type\GroupFormType
    tags:
      - { name: form.type, alias: fly_user_group }

#  fly.registration.form.type:
#    class: Fly\UserBundle\Form\Type\RegistrationFormType
#    arguments: [%fos_user.model.user.class%]
#    tags: [{ name: "form.type", alias: "fly_user_registration" }]
#
#  fly.invitation.form.type:
#    class: Fly\UserBundle\Form\Type\InvitationFormType
#    arguments: [@fly.invitation.form.data_transformer]
#    tags: [{ name: "form.type", alias: "fly_invitation_type" }]
#
#  fly.invitation.email.form.type:
#      class: Fly\UserBundle\Form\Type\InvitationEmailFormType
#      arguments: [@fly.invitation.form.email.data_transformer]
#      tags: [{ name: "form.type", alias: "fly_invitation_email_type" }]
#
#  fly.invitation.form.data_transformer:
#    class: Fly\UserBundle\Form\DataTransformer\InvitationToCodeTransformer
#    arguments: [@doctrine.orm.entity_manager]
#  fly.invitation.form.email.data_transformer:
#      class: Fly\UserBundle\Form\DataTransformer\InvitationToEmailTransformer
#      arguments: [@doctrine.orm.entity_manager]
#
  fly.invitation.sender:
    class: Fly\UserBundle\Service\InvitationSender
    arguments: [@swiftmailer.mailer,@router, @doctrine.orm.entity_manager,@templating.engine.twig]

  fly.user.feed:
      class:  Fly\UserBundle\Service\Feed
      arguments: [@gremo_buzz]
  fly.registration.form.type:
      class:  Fly\UserBundle\Form\Type\RegistrationFormType
      tags:
          - { name: form.type, alias: fly_user_registration }
  fly.user.register.service:
    class: Fly\UserBundle\Service\RegisterService
    arguments: [@swiftmailer.mailer,@router, @doctrine.orm.entity_manager,@templating.engine.twig]
  fly.user.facebook.service:
    class: Fly\UserBundle\Service\FacebookService
    arguments: [@swiftmailer.mailer,@router, @doctrine.orm.entity_manager,@templating.engine.twig]
  fos_user.doctrine_registry:
    alias: doctrine
  fly.user.service:
    class: Fly\UserBundle\Service\UserService
    arguments: [@router, @doctrine.orm.entity_manager,]

  fly.step.form:
    class: Fly\UserBundle\Service\StepForm
    arguments: [@doctrine.orm.entity_manager]

  fly.feed_resource.delete:
    class: Fly\UserBundle\DoctrineListener\FeedResourceRemove
    tags:
        - { name: doctrine.event_listener, event: postRemove }

  fly.group.delete:
    class: Fly\UserBundle\DoctrineListener\GroupRemove
    tags:
        - { name: doctrine.event_listener, event: postRemove }

  fly.user.notification.service:
    class: Fly\UserBundle\Service\NotificationService
    arguments: [@router, @doctrine.orm.entity_manager]